---
title: "Old Faithful"
output: flexdashboard::flex_dashboard
runtime: shinyrmd
---

```{r context="setup",include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
x <- faithful$waiting
```

Column {.sidebar}
-------------------------------------------------------------

```{r context="render"}
sliderInput(
  inputId = "n",
  label = "Number of bins:",
  min = 1,
  max = 50,
  value = 25,
  ticks = TRUE
)
```

Column
-------------------------------------------------------------

This is a dynamic document with:

- Rmarkdown, and
- Runtime: `shinyrmd`.

```{r context="render"}
plotOutput("histogram")
```

```{r context="server"}
output$histogram <- renderPlot(
  alt = "Histogram of waiting times",
  {
    hist(
      x,
      breaks = seq(min(x), max(x),
        length.out = input$n + 1
      ),
      freq = TRUE,
      col = "#BB74DB",
      border = "white",
      main = "Histogram of waiting times",
      xlab = "Waiting time to next eruption [mins]",
      ylab = "Frequency"
    )
    box()
  }
)
```
