FROM rocker/r2u:24.04 AS builder
RUN install.r shinylive
WORKDIR /root
COPY r-shiny/app app
RUN R -q -e "shinylive::export('app', 'output')"

FROM ghcr.io/openfaas/of-watchdog:0.10.1 AS watchdog

FROM alpine:3.20
COPY --from=builder /root/output /app
COPY --from=watchdog /fwatchdog .
ENV mode="static"
ENV static_path="/app"
HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1
CMD ["./fwatchdog"]
