name: Build and Push Docker Image for faithful/r-shiny

on:
  push:
    branches: [ "main" ]
    paths: [ "r-shiny/**"]
  pull_request:
    branches: [ "main" ]
    paths: [ "r-shiny/**"]

env:
  SHINY_SETUP: r-shiny
  TAG: latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Docker metadata'
        id: meta
        uses: docker/metadata-action@v5
        with:
          labels: |
            maintainer=Peter Solymos
            org.opencontainers.image.title=Faithful
            org.opencontainers.image.description=Old Faithful Shiny app version ${SHINY_SETUP}
            org.opencontainers.image.vendor=Hosting Shiny Book Project

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and push'
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.SHINY_SETUP }}
          file: ./${{ env.SHINY_SETUP }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.SHINY_SETUP }}:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}
